# Generated by Django 6.0.4 on 2026-04-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/%Y/%m/', verbose_name='Rasm (ixtiyoriy)'),
        ),
    ]
