# Generated by Django 6.0.4 on 2026-05-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_builder', '0003_add_choice_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(blank=True, max_length=500, verbose_name='Variant matni'),
        ),
    ]
