# Generated by Django 6.0.4 on 2026-04-13 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('test_builder', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/', verbose_name='Fayl')),
                ('original_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('parsed', 'Parse qilindi'), ('failed', 'Xato'), ('imported', 'Testga aylantirildi')], default='pending', max_length=16)),
                ('parsed_count', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_jobs', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_jobs', to='test_builder.test')),
            ],
            options={
                'verbose_name': 'Yuklangan fayl',
                'verbose_name_plural': 'Yuklangan fayllar',
                'ordering': ['-created_at'],
            },
        ),
    ]
